name: Deploy
on:
    push:
        branches: [main]
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        
        - uses: actions/checkout@v2

        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images:  gotify/server:latest
            tag-sha: true

        - name: QEMU
          uses: docker/setup-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME}}
            password: ${{ secrets.DOCKERHUB_TOKEN}}


        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64, linux386
            tags: ${{ steps.docker_meta.outputs.tags}}
            lables: ${{ steps.docker_meta.outputs.labels}}

        - name: set deployment images
          run: kubectl set image deployment goserver goserver=gotify/server:${{ steps.docker_meta.outputs.tags}}
